import { PrismaClient, Role, KycStatus } from '@prisma/client'
import * as bcrypt from 'bcrypt'

const prisma = new PrismaClient()

async function main() {
  // ─── 1. Compte ADMIN ────────────────────────────────────────────────────────
  const adminPassword = await bcrypt.hash('Admin1234!', 10)

  await prisma.user.upsert({
    where: { email: 'admin@investbf.com' },
    update: {},
    create: {
      email: 'admin@investbf.com',
      password: adminPassword,
      firstName: 'Super',
      lastName: 'Admin',
      role: Role.ADMIN,
      kycStatus: KycStatus.APPROVED,
      balance: 0,
    },
  })
  console.log('✔ Admin créé : admin@investbf.com / Admin1234!')

  // ─── 2. Offres d'investissement ─────────────────────────────────────────────
  const offerings = [
    {
      name: 'TechBF SA',
      sector: 'Technologie',
      pricePerShare: 5000,
      totalShares: 1000,
      soldShares: 340,
      minInvest: 25000,
      description: 'Startup burkinabè spécialisée dans les solutions de paiement mobile pour les PME.',
      riskLevel: 'Moyen',
      isOpen: true,
    },
    {
      name: 'AgroSahel',
      sector: 'Agriculture',
      pricePerShare: 2500,
      totalShares: 2000,
      soldShares: 1200,
      minInvest: 12500,
      description: 'Coopérative agricole produisant et exportant des produits céréaliers au Sahel.',
      riskLevel: 'Faible',
      isOpen: true,
    },
    {
      name: 'SolarBF',
      sector: 'Énergie',
      pricePerShare: 7500,
      totalShares: 500,
      soldShares: 50,
      minInvest: 37500,
      description: 'Installation de panneaux solaires pour les zones rurales non connectées au réseau.',
      riskLevel: 'Élevé',
      isOpen: true,
    },
    {
      name: 'BanqueVerte',
      sector: 'Finance',
      pricePerShare: 10000,
      totalShares: 800,
      soldShares: 600,
      minInvest: 50000,
      description: 'Microfinance dédiée aux femmes entrepreneures au Burkina Faso.',
      riskLevel: 'Faible',
      isOpen: true,
    },
    {
      name: 'ClinicGroup',
      sector: 'Santé',
      pricePerShare: 6000,
      totalShares: 600,
      soldShares: 120,
      minInvest: 30000,
      description: 'Réseau de cliniques privées abordables dans les villes secondaires.',
      riskLevel: 'Moyen',
      isOpen: true,
    },
    {
      name: 'EduBF Academy',
      sector: 'Éducation',
      pricePerShare: 3000,
      totalShares: 1500,
      soldShares: 450,
      minInvest: 15000,
      description: 'Plateforme d\'e-learning en langues locales (mooré, dioula) pour les lycéens burkinabè.',
      riskLevel: 'Moyen',
      isOpen: true,
    },
    {
      name: 'TransLog BF',
      sector: 'Transport & Logistique',
      pricePerShare: 4500,
      totalShares: 1200,
      soldShares: 300,
      minInvest: 22500,
      description: 'Service de livraison last-mile pour les e-commerces et supermarchés de Ouagadougou.',
      riskLevel: 'Moyen',
      isOpen: true,
    },
    {
      name: 'AquaBF',
      sector: 'Eau & Environnement',
      pricePerShare: 8000,
      totalShares: 400,
      soldShares: 80,
      minInvest: 40000,
      description: 'Systèmes d\'irrigation intelligente et de traitement de l\'eau potable pour les communes rurales.',
      riskLevel: 'Élevé',
      isOpen: true,
    },
    {
      name: 'ImmoBF Résidences',
      sector: 'Immobilier',
      pricePerShare: 15000,
      totalShares: 300,
      soldShares: 210,
      minInvest: 75000,
      description: 'Promotion immobilière de logements abordables dans les nouveaux quartiers de Bobo-Dioulasso.',
      riskLevel: 'Faible',
      isOpen: true,
    },
    {
      name: 'ColdChain Sahel',
      sector: 'Agroalimentaire',
      pricePerShare: 5500,
      totalShares: 700,
      soldShares: 140,
      minInvest: 27500,
      description: 'Réseau de chambres froides solaires pour réduire les pertes post-récolte des maraîchers.',
      riskLevel: 'Moyen',
      isOpen: false,
    },
    {
      name: 'MinesBF Resources',
      sector: 'Mines & Extraction',
      pricePerShare: 20000,
      totalShares: 250,
      soldShares: 60,
      minInvest: 100000,
      description: 'Société artisanale d\'extraction et de valorisation de l\'or et du manganèse dans l\'Ouest du Burkina.',
      riskLevel: 'Élevé',
      isOpen: true,
    },
    {
      name: 'BF Média Group',
      sector: 'Médias & Communication',
      pricePerShare: 3500,
      totalShares: 900,
      soldShares: 270,
      minInvest: 17500,
      description: 'Groupe de presse multicanal (radio, web, TV locale) couvrant les 13 régions du Burkina Faso.',
      riskLevel: 'Moyen',
      isOpen: true,
    },
    {
      name: 'SahelTour',
      sector: 'Tourisme & Hôtellerie',
      pricePerShare: 9000,
      totalShares: 350,
      soldShares: 105,
      minInvest: 45000,
      description: 'Éco-lodges et circuits culturels valorisant le patrimoine Mossi, Lobi et Bobo à destination des touristes africains.',
      riskLevel: 'Moyen',
      isOpen: true,
    },
    {
      name: 'BatiSahel BTP',
      sector: 'Construction & BTP',
      pricePerShare: 6500,
      totalShares: 800,
      soldShares: 320,
      minInvest: 32500,
      description: 'Entreprise de construction de bâtiments publics et de routes rurales avec des matériaux locaux biosourcés.',
      riskLevel: 'Faible',
      isOpen: true,
    },
    {
      name: 'FasoTextile',
      sector: 'Textile & Artisanat',
      pricePerShare: 2000,
      totalShares: 3000,
      soldShares: 900,
      minInvest: 10000,
      description: 'Filière complète de production et d\'exportation du tissu Faso Danfani, du fil de coton au prêt-à-porter.',
      riskLevel: 'Faible',
      isOpen: true,
    },
    {
      name: 'DataSahel Analytics',
      sector: 'Numérique & Data',
      pricePerShare: 12000,
      totalShares: 200,
      soldShares: 40,
      minInvest: 60000,
      description: 'Plateforme SaaS d\'analyse de données agricoles et climatiques pour les ONG et gouvernements africains.',
      riskLevel: 'Élevé',
      isOpen: true,
    },
    {
      name: 'BetailBF',
      sector: 'Élevage',
      pricePerShare: 3000,
      totalShares: 1800,
      soldShares: 540,
      minInvest: 15000,
      description: 'Ferme moderne d\'élevage bovin et ovin avec chaîne de transformation frigorifique à Dori.',
      riskLevel: 'Moyen',
      isOpen: true,
    },
    {
      name: 'Café Faso Premium',
      sector: 'Agroalimentaire',
      pricePerShare: 4000,
      totalShares: 600,
      soldShares: 0,
      minInvest: 20000,
      description: 'Torréfaction et commercialisation de cafés spéciaux burkinabè vers les marchés européens et du Golfe.',
      riskLevel: 'Moyen',
      isOpen: true,
    },
    {
      name: 'E-Santé BF',
      sector: 'Santé Digitale',
      pricePerShare: 7000,
      totalShares: 500,
      soldShares: 75,
      minInvest: 35000,
      description: 'Application mobile de téléconsultation médicale et de gestion du dossier patient pour les zones rurales.',
      riskLevel: 'Élevé',
      isOpen: true,
    },
    {
      name: 'FormaPro Sahel',
      sector: 'Formation Professionnelle',
      pricePerShare: 2500,
      totalShares: 1200,
      soldShares: 360,
      minInvest: 12500,
      description: 'Centres de formation aux métiers du numérique, de la mécanique et du bâtiment pour les jeunes de 16-25 ans.',
      riskLevel: 'Faible',
      isOpen: true,
    },
  ]

  // Supprime les offres sans souscription puis recrée tout (idempotent)
  await prisma.offering.deleteMany({ where: { subs: { none: {} } } })
  await prisma.offering.createMany({ data: offerings })
  console.log(`✔ ${offerings.length} offres d'investissement chargées`)
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
